FROM maven:latest as build
COPY pom.xml demo/pom.xml
COPY UserCatalog/pom.xml demo/UserCatalog/pom.xml
COPY UserCatalog/src demo/UserCatalog/src
RUN mvn -f demo/UserCatalog/pom.xml clean package -DskipTests

FROM java:latest

WORKDIR /src/java
EXPOSE 8080
COPY --from=build demo/UserCatalog/target/UserCatalog-0.0.1-SNAPSHOT.jar /opt/demo/UserCatalog/UserCatalog-0.0.1-SNAPSHOT.jar
CMD ["java", "-jar", "/opt/demo/UserCatalog/UserCatalog-0.0.1-SNAPSHOT.jar"]